version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y python3-pip
      - pip3 install pylint  # Install Pylint

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - pip3 install -r requirements.txt

  build:
    commands:
      - echo "Checking directory structure..."
      - ls -R  # Debugging step to verify file paths
      - echo "Running Pylint for Static Code Analysis..."
      # Ensure we are in the correct directory before running Pylint
      - cd quiz_project
      - pylint --disable=C --fail-under=9 $(find . -name "*.py") || exit 1

artifacts:
  files: "**/*"
