version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9  # Adjust based on your project's requirements
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-cov  # Install pytest and coverage tool
 
  pre_build:
    commands:
      - echo "Pre-build phase..."
 
  build:
    commands:
      - echo "Running tests with pytest..."
      - pytest --junitxml=test-results.xml --cov=quiz_project  # Adjust project name
 
  post_build:
    commands:
      - echo "Build completed."
 
artifacts:
  files:
    - test-results.xml  # Store test results for reporting
    - '**/*.log'
  discard-paths: yes
